;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #3F3F3F
background-alt = #373B41
foreground = #C5C8C6
primary = #10b1fe
secondary = #28e4eb
alert = #A54242
disabled = #707880

background-transparent = #00000000

;==============================================================================
[bar/left]
width = 50%
height = 24pt
radius = 12pt
offset-x = 1%

border-size = 4pt
border-color = ${colors.background-transparent}

separator = |
separator-foreground = ${colors.background}
separator-background = ${colors.background}

background = ${colors.background}

font-0 = "Google Sans Mono:size=12;2"
font-1 = "Symbols Nerd Font:size=12;2"

enable-ipc = true
wm-restack = i3

modules-left = xworkspaces
modules-center = clock date
modules-right = network cpu memory filesystem empty
;==============================================================================
[bar/center]
width = 10%
height = 24pt
radius = 12pt

border-size = 4pt
border-color = ${colors.background-transparent}

background = ${colors.background-transparent}

font-0 = "Google Sans Mono:size=12;2"
font-1 = "Symbols Nerd Font:size=12;2"

offset-x = 45% ; Căn giữa màn hình
offset-y = 0.5%

modules-center = clock date
;==============================================================================
[bar/right]
width = 15%
height = 24pt
radius = 12pt

border-size = 4pt
border-color = ${colors.background-transparent}

background = ${colors.background-transparent}

font-0 = "Google Sans Mono:size=12;2"
font-1 = "Symbols Nerd Font:size=12;2"

separator = |
separator-foreground = ${colors.disabled}
separator-background = ${colors.background}

offset-x = 51%

modules-right = network cpu memory filesystem 
;==============================================================================

; $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ MODULES $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

;------------------------------------------------------------------------------
[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt
;------------------------------------------------------------------------------
[module/xworkspaces]
type = internal/xworkspaces

format-background = ${colors.background}

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1
;------------------------------------------------------------------------------
[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%
;------------------------------------------------------------------------------
[module/filesystem]
type = internal/fs
interval = 60

mount-0 = /

format-mounted-suffix = " "

format-mounted-prefix = "  "
format-mounted-prefix-foreground = ${colors.primary}
format-mounted-background = ${colors.background}

label-mounted = %used%
label-mounted-background = ${colors.background}
;------------------------------------------------------------------------------
[module/memory]
type = internal/memory
interval = 2

format-prefix = "  "
format-prefix-foreground = ${colors.primary}
format-prefix-background = ${colors.background}

label = %used%
label-background = ${colors.background}
;------------------------------------------------------------------------------
[module/cpu]
type = internal/cpu
interval = 2

format-prefix = "  "
format-prefix-foreground = ${colors.primary}
format-prefix-background = ${colors.background}

label = %percentage:2%%
label-background = ${colors.background}
;------------------------------------------------------------------------------
[module/clock]
type = internal/date
interval = 1

format-prefix = "  " 
format-prefix-foreground = ${colors.primary}

date = %I:%M %p
date-alt = %Y-%m-%d %I:%M:%S %p

label = %date%
label-background = ${colors.background}
;------------------------------------------------------------------------------
[module/date]
type = internal/date
interval = 1

format-prefix = "  " 
format-prefix-foreground = ${colors.primary}

date = %d/%m/%Y
date-alt = %Y-%m-%d %I:%M:%S %p

label = %date%
label-background = ${colors.background}
; label-foreground = ${colors.primary}
;------------------------------------------------------------------------------
[module/network]
type = internal/network
interface = eth1
interval = 1.0

format-prefix = "%{F#1e1e2e}%{F-}"

label-connected = %{F#10b1fe}%{T2}%{T-} %{F-}%downspeed:9% %{F#10b1fe}%{T2}%{T-} %{F-}%upspeed:9%
label-connected-background = ${colors.background}

label-disconnected = %{T2}󰅛%{T-} Disconnected
label-disconnected-foreground = ${colors.disabled}
;------------------------------------------------------------------------------
[module/empty]
